/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  // Safelist the dynamic color classes generated by template literals
  // in our PathCard, StatCard, DetailBox, MetricTile components so Tailwind
  // doesn't purge them during production build.
  safelist: [
    // Gradients used by PathCard
    { pattern: /^from-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(50|100|500|600|700)$/ },
    { pattern: /^to-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(50|100|500|600|700)$/ },
    { pattern: /^bg-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(50|100|200|300|500|600|700|800|900)$/ },
    { pattern: /^text-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(50|100|200|300|500|600|700|800|900)$/ },
    { pattern: /^border-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(100|200|300|400|500)$/ },
    { pattern: /^hover:border-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(300|400|500)$/ },
    { pattern: /^hover:bg-(indigo|purple|emerald|rose|amber|blue|sky|violet|slate|pink|teal)-(50|100|600|700)$/ },
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
